# Generated by Django 2.1 on 2018-12-20 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Комментарий')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('awful', 'Посредственно'), ('bad', 'Неудовлетворительно'), ('average', 'Удовлетворительно'), ('well', 'Хорошо'), ('excellent', 'Отлично')], max_length=20, verbose_name='Оценка')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='webapp.Post', verbose_name='Пост')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favored_by', to='webapp.Post', verbose_name='Избранное')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='webapp.User', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_by_user', to='webapp.User', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webapp.User', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_comments', to='webapp.Comment', verbose_name='Родительский комментарий'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webapp.Post', verbose_name='Пост'),
        ),
    ]
